version: '3.8'
services:
  fileupload:
    container_name: 'fileupload'
    image: fileupload:1.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '3014:8080'
    volumes:
      - '/home/automatex/deployment/file-upload:/images'
# networks:
#   default:
#     external: true
#     name: ecommerce_store-net
